language: c

compiler:
   - gcc

addons:
  sonarcloud:
    organization: "lexel225-sonar"
    token: $SONAR_TOKEN

script: 
   - build-wrapper-linux-x86-64 --out-dir build_wrapper_output_directory make clean all
   - make
   - sonar-scanner

after_success: ./run

after_script: make clean
