language: c

compiler:
   - gcc

addons:
  sonarcloud:
    organization: "lexel225-sonar"
    token: $SONAR_TOKEN

script: 
   - make
   - sonar-scanner

after_success: ./run

after_script: make clean
